<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MedicineListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing products first
        DB::table('products')->truncate();

        $medicines = [
            // Vitamins Category
            [
                'name' => 'ASCORBIC ACID (MYREVIT C) 120 ML',
                'description' => 'Vitamin C syrup for immune system support',
                'price' => 85.00,
                'image' => 'assets/img/vitamin-c.jpg',
                'category' => 'vitamins',
                'brand' => 'Myrevit',
                'sku' => 'VIT-C-120',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '120ml',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Myrevit',
                'rating' => 4.6,
                'review_count' => 95,
                'tags' => json_encode(['vitamin c', 'immune system', 'antioxidant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ASCORBIC ACID (MYREVIT C) 60 ML',
                'description' => 'Vitamin C syrup for immune system support',
                'price' => 45.00,
                'image' => 'assets/img/vitamin-c.jpg',
                'category' => 'vitamins',
                'brand' => 'Myrevit',
                'sku' => 'VIT-C-60',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '60ml',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Myrevit',
                'rating' => 4.6,
                'review_count' => 78,
                'tags' => json_encode(['vitamin c', 'immune system', 'antioxidant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ascorbic (ASCOPHIL) 500mg Tablet',
                'description' => 'Vitamin C tablet for daily supplementation',
                'price' => 35.00,
                'image' => 'assets/img/vitamin-c.jpg',
                'category' => 'vitamins',
                'brand' => 'Ascophil',
                'sku' => 'ASCO-500-30',
                'stock_quantity' => 200,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Ascophil',
                'rating' => 4.5,
                'review_count' => 156,
                'tags' => json_encode(['vitamin c', 'immune system', 'antioxidant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ceelin Chewable 30s/bot (Ascorbic)',
                'description' => 'Chewable Vitamin C tablets for children',
                'price' => 75.00,
                'image' => 'assets/img/ceelin.jpg',
                'category' => 'vitamins',
                'brand' => 'Ceelin',
                'sku' => 'CEL-CHEW-30',
                'stock_quantity' => 150,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '30 tablets',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Ceelin',
                'rating' => 4.7,
                'review_count' => 203,
                'tags' => json_encode(['vitamin c', 'children', 'chewable']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Multivitamins (MYREVIT) Capsule',
                'description' => 'Complete multivitamin supplement for daily health',
                'price' => 75.00,
                'image' => 'assets/img/multivitamin.jpg',
                'category' => 'vitamins',
                'brand' => 'Myrevit',
                'sku' => 'MULTI-30',
                'stock_quantity' => 180,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 capsule daily',
                'active_ingredient' => 'Multivitamin Complex',
                'manufacturer' => 'Myrevit',
                'rating' => 4.4,
                'review_count' => 167,
                'tags' => json_encode(['multivitamin', 'daily supplement', 'health']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Potencee Forte 1000mg',
                'description' => 'High potency Vitamin C for immune support',
                'price' => 95.00,
                'image' => 'assets/img/vitamin-c.jpg',
                'category' => 'vitamins',
                'brand' => 'Potencee',
                'sku' => 'POT-1000-30',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1000mg',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Potencee',
                'rating' => 4.6,
                'review_count' => 134,
                'tags' => json_encode(['vitamin c', 'high potency', 'immune system']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vit. B-Complex (AMCOVIT-B) Tablet',
                'description' => 'B-complex vitamins for energy and metabolism',
                'price' => 65.00,
                'image' => 'assets/img/b-complex.jpg',
                'category' => 'vitamins',
                'brand' => 'Amcovit',
                'sku' => 'B-COMP-30',
                'stock_quantity' => 160,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet daily',
                'active_ingredient' => 'B-Complex Vitamins',
                'manufacturer' => 'Amcovit',
                'rating' => 4.3,
                'review_count' => 98,
                'tags' => json_encode(['b-complex', 'energy', 'metabolism']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Medicines Category
            [
                'name' => 'Biogesic 500mg tab',
                'description' => 'Paracetamol 500mg tablet for fever and pain relief',
                'price' => 50.00,
                'image' => 'assets/img/biogesic.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'BIO-500-20',
                'stock_quantity' => 150,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Paracetamol',
                'manufacturer' => 'Unilab',
                'rating' => 4.5,
                'review_count' => 128,
                'tags' => json_encode(['pain relief', 'fever', 'headache']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Advil Liquigel (Ibuprofen) Capsule',
                'description' => 'Ibuprofen capsules for pain relief and inflammation',
                'price' => 75.00,
                'image' => 'assets/img/advil.jpg',
                'category' => 'medicines',
                'brand' => 'Pfizer',
                'sku' => 'ADV-200-20',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '200mg',
                'active_ingredient' => 'Ibuprofen',
                'manufacturer' => 'Pfizer',
                'rating' => 4.4,
                'review_count' => 95,
                'tags' => json_encode(['pain relief', 'inflammation', 'fever']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alaxan FR',
                'description' => 'Combination pain reliever for fever and pain',
                'price' => 65.00,
                'image' => 'assets/img/alaxan.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'ALX-FR-20',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet as needed',
                'active_ingredient' => 'Paracetamol + Ibuprofen',
                'manufacturer' => 'Unilab',
                'rating' => 4.3,
                'review_count' => 87,
                'tags' => json_encode(['pain relief', 'fever', 'combination']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Allerkid (Cetirizine) 2.5mg/10ml Drops',
                'description' => 'Antihistamine drops for children with allergies',
                'price' => 95.00,
                'image' => 'assets/img/allerkid.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'ALK-2.5-15',
                'stock_quantity' => 80,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '2.5mg/10ml',
                'active_ingredient' => 'Cetirizine',
                'manufacturer' => 'Unilab',
                'rating' => 4.5,
                'review_count' => 112,
                'tags' => json_encode(['allergy', 'antihistamine', 'children']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ASCOF 600mg 120ml Syrup',
                'description' => 'Herbal cough syrup with lagundi extract',
                'price' => 75.00,
                'image' => 'assets/img/ascof.jpg',
                'category' => 'medicines',
                'brand' => 'ASCOF',
                'sku' => 'ASCOF-600-120',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '600mg/5ml',
                'active_ingredient' => 'Lagundi Extract',
                'manufacturer' => 'ASCOF',
                'rating' => 4.6,
                'review_count' => 156,
                'tags' => json_encode(['cough', 'herbal', 'lagundi']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bioflu Tablet',
                'description' => 'Combination medicine for flu symptoms',
                'price' => 55.00,
                'image' => 'assets/img/bioflu.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'BIOFLU-20',
                'stock_quantity' => 140,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet as needed',
                'active_ingredient' => 'Paracetamol + Phenylephrine + Chlorphenamine',
                'manufacturer' => 'Unilab',
                'rating' => 4.5,
                'review_count' => 189,
                'tags' => json_encode(['flu', 'cold', 'fever']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Decolgen Forte',
                'description' => 'Decongestant for nasal congestion and cold symptoms',
                'price' => 45.00,
                'image' => 'assets/img/decolgen.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'DEC-FORTE-20',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet as needed',
                'active_ingredient' => 'Paracetamol + Phenylephrine + Chlorphenamine',
                'manufacturer' => 'Unilab',
                'rating' => 4.4,
                'review_count' => 134,
                'tags' => json_encode(['cold', 'decongestant', 'nasal']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Neozep Forte',
                'description' => 'Combination medicine for cold and flu symptoms',
                'price' => 50.00,
                'image' => 'assets/img/neozep.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'NEO-FORTE-20',
                'stock_quantity' => 110,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet as needed',
                'active_ingredient' => 'Paracetamol + Phenylephrine + Chlorphenamine',
                'manufacturer' => 'Unilab',
                'rating' => 4.3,
                'review_count' => 98,
                'tags' => json_encode(['cold', 'flu', 'fever']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Solmux 200mg 60ml',
                'description' => 'Cough medicine for productive cough',
                'price' => 65.00,
                'image' => 'assets/img/solmux.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'SOL-200-60',
                'stock_quantity' => 90,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '200mg/5ml',
                'active_ingredient' => 'Carbocisteine',
                'manufacturer' => 'Unilab',
                'rating' => 4.5,
                'review_count' => 167,
                'tags' => json_encode(['cough', 'productive', 'mucolytic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tempra Drops 15ml Orange',
                'description' => 'Paracetamol drops for children fever and pain',
                'price' => 85.00,
                'image' => 'assets/img/tempra.jpg',
                'category' => 'medicines',
                'brand' => 'Tempra',
                'sku' => 'TEMP-DROPS-15',
                'stock_quantity' => 75,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '15ml bottle',
                'active_ingredient' => 'Paracetamol',
                'manufacturer' => 'Tempra',
                'rating' => 4.7,
                'review_count' => 203,
                'tags' => json_encode(['fever', 'pain relief', 'children']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vicks Vaporub 10g',
                'description' => 'Topical ointment for cough and cold relief',
                'price' => 35.00,
                'image' => 'assets/img/vicks.jpg',
                'category' => 'medicines',
                'brand' => 'Vicks',
                'sku' => 'VICKS-10G',
                'stock_quantity' => 200,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => 'Apply to chest and throat',
                'active_ingredient' => 'Menthol + Camphor + Eucalyptus',
                'manufacturer' => 'Vicks',
                'rating' => 4.6,
                'review_count' => 289,
                'tags' => json_encode(['cough', 'cold', 'topical']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Centrum Advance tab',
                'description' => 'Complete multivitamin supplement for adults',
                'price' => 125.00,
                'image' => 'assets/img/centrum.jpg',
                'category' => 'vitamins',
                'brand' => 'Centrum',
                'sku' => 'CENT-ADV-30',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet daily',
                'active_ingredient' => 'Multivitamin Complex',
                'manufacturer' => 'Centrum',
                'rating' => 4.5,
                'review_count' => 234,
                'tags' => json_encode(['multivitamin', 'adults', 'complete']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Enervon C Tablet x 30s',
                'description' => 'Vitamin C supplement for energy and immunity',
                'price' => 95.00,
                'image' => 'assets/img/enervon.jpg',
                'category' => 'vitamins',
                'brand' => 'Enervon',
                'sku' => 'ENERVON-C-30',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1 tablet daily',
                'active_ingredient' => 'Ascorbic Acid + B-Complex',
                'manufacturer' => 'Enervon',
                'rating' => 4.4,
                'review_count' => 178,
                'tags' => json_encode(['vitamin c', 'energy', 'immunity']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Additional Medicines from Your List
            [
                'name' => 'Betadine 15ml Solution',
                'description' => 'Antiseptic solution for wound cleaning',
                'price' => 45.00,
                'image' => 'assets/img/betadine.jpg',
                'category' => 'medicines',
                'brand' => 'Betadine',
                'sku' => 'BET-15',
                'stock_quantity' => 180,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => 'Apply as needed',
                'active_ingredient' => 'Povidone-Iodine',
                'manufacturer' => 'Betadine',
                'rating' => 4.7,
                'review_count' => 234,
                'tags' => json_encode(['antiseptic', 'wound care', 'disinfectant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all medicines
        DB::table('products')->insert($medicines);

        $this->command->info('Successfully seeded ' . count($medicines) . ' medicines and vitamins!');
    }
}
