<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing products
        DB::table('products')->truncate();

        $products = [
            // Medicines Category
            [
                'name' => 'Biogesic 500mg',
                'description' => 'Paracetamol 500mg tablet for fever and pain relief',
                'price' => 50.00,
                'image' => 'assets/img/biogesic.jpg',
                'category' => 'medicines',
                'brand' => 'Unilab',
                'sku' => 'BIO-500-20',
                'stock_quantity' => 150,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Paracetamol',
                'manufacturer' => 'Unilab',
                'rating' => 4.5,
                'review_count' => 128,
                'tags' => json_encode(['pain relief', 'fever', 'headache']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Advil 200mg',
                'description' => 'Ibuprofen tablets for pain relief and inflammation',
                'price' => 75.00,
                'image' => 'assets/img/advil.jpg',
                'category' => 'medicines',
                'brand' => 'Pfizer',
                'sku' => 'ADV-200-20',
                'stock_quantity' => 120,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '200mg',
                'active_ingredient' => 'Ibuprofen',
                'manufacturer' => 'Pfizer',
                'rating' => 4.4,
                'review_count' => 95,
                'tags' => json_encode(['pain relief', 'inflammation', 'fever']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tylenol 500mg',
                'description' => 'Acetaminophen tablets for fever and pain relief',
                'price' => 65.00,
                'image' => 'assets/img/tylenol.jpg',
                'category' => 'medicines',
                'brand' => 'Johnson & Johnson',
                'sku' => 'TYL-500-24',
                'stock_quantity' => 80,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Acetaminophen',
                'manufacturer' => 'Johnson & Johnson',
                'rating' => 4.6,
                'review_count' => 142,
                'tags' => json_encode(['pain relief', 'fever', 'safe']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aspirin 325mg',
                'description' => 'Low-dose aspirin for heart health and pain relief',
                'price' => 35.00,
                'image' => 'assets/img/aspirin.jpg',
                'category' => 'medicines',
                'brand' => 'Bayer',
                'sku' => 'ASP-325-100',
                'stock_quantity' => 200,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '325mg',
                'active_ingredient' => 'Acetylsalicylic Acid',
                'manufacturer' => 'Bayer',
                'rating' => 4.3,
                'review_count' => 78,
                'tags' => json_encode(['heart health', 'pain relief', 'blood thinner']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mefenamic Acid 500mg',
                'description' => 'Anti-inflammatory medicine for pain and fever',
                'price' => 45.00,
                'image' => 'assets/img/mefenamic.jpg',
                'category' => 'medicines',
                'brand' => 'Generics',
                'sku' => 'MEF-500-10',
                'stock_quantity' => 90,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Mefenamic Acid',
                'manufacturer' => 'Generics Pharmacy',
                'rating' => 4.2,
                'review_count' => 67,
                'tags' => json_encode(['pain relief', 'inflammation', 'menstrual pain']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Vitamins Category
            [
                'name' => 'Vitamin C 500mg',
                'description' => 'High-potency Vitamin C supplement for immune system support',
                'price' => 15.00,
                'image' => 'assets/img/vitamin-c.jpg',
                'category' => 'vitamins',
                'brand' => 'Centrum',
                'sku' => 'VIT-C-500-30',
                'stock_quantity' => 200,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '500mg',
                'active_ingredient' => 'Ascorbic Acid',
                'manufacturer' => 'Pfizer',
                'rating' => 4.3,
                'review_count' => 89,
                'tags' => json_encode(['vitamin', 'immunity', 'antioxidant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Multivitamins Complete',
                'description' => 'Complete daily multivitamin with minerals',
                'price' => 450.00,
                'image' => 'assets/img/multivitamins.jpg',
                'category' => 'vitamins',
                'brand' => 'Centrum',
                'sku' => 'MUL-COM-30',
                'stock_quantity' => 60,
                'is_available' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Pfizer',
                'rating' => 4.5,
                'review_count' => 203,
                'tags' => json_encode(['multivitamin', 'daily nutrition', 'minerals']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vitamin D3 1000IU',
                'description' => 'High-potency Vitamin D3 for bone health',
                'price' => 320.00,
                'image' => 'assets/img/vitamin-d3.jpg',
                'category' => 'vitamins',
                'brand' => 'Nature Made',
                'sku' => 'VIT-D3-1000-60',
                'stock_quantity' => 90,
                'is_available' => true,
                'requires_prescription' => false,
                'dosage' => '1000IU',
                'active_ingredient' => 'Cholecalciferol',
                'manufacturer' => 'Nature Made',
                'rating' => 4.7,
                'review_count' => 156,
                'tags' => json_encode(['vitamin d', 'bone health', 'immunity']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Omega-3 Fish Oil',
                'description' => 'Premium fish oil capsules for heart and brain health',
                'price' => 680.00,
                'image' => 'assets/img/omega3.jpg',
                'category' => 'vitamins',
                'brand' => 'Nordic Naturals',
                'sku' => 'OME-3-120',
                'stock_quantity' => 45,
                'is_available' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Nordic Naturals',
                'rating' => 4.8,
                'review_count' => 234,
                'tags' => json_encode(['omega 3', 'heart health', 'brain health']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Calcium + Vitamin D',
                'description' => 'Calcium supplement with Vitamin D for bone strength',
                'price' => 280.00,
                'image' => 'assets/img/calcium.jpg',
                'category' => 'vitamins',
                'brand' => 'Caltrate',
                'sku' => 'CAL-VD-60',
                'stock_quantity' => 75,
                'is_available' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Pfizer',
                'rating' => 4.4,
                'review_count' => 112,
                'tags' => json_encode(['calcium', 'bone health', 'vitamin d']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // First Aid Category
            [
                'name' => 'Betadine Solution 60ml',
                'description' => 'Antiseptic solution for wound cleaning and disinfection',
                'price' => 85.00,
                'image' => 'assets/img/betadine.jpg',
                'category' => 'first_aid',
                'brand' => 'Betadine',
                'sku' => 'BET-SOL-60',
                'stock_quantity' => 75,
                'is_available' => true,
                'requires_prescription' => false,
                'active_ingredient' => 'Povidone Iodine',
                'manufacturer' => 'Mundipharma',
                'rating' => 4.7,
                'review_count' => 156,
                'tags' => json_encode(['antiseptic', 'wound care', 'disinfectant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alcohol 70% 500ml',
                'description' => 'Isopropyl alcohol for disinfection and cleaning',
                'price' => 45.00,
                'image' => 'assets/img/alcohol.jpg',
                'category' => 'first_aid',
                'brand' => 'Green Cross',
                'sku' => 'ALC-70-500',
                'stock_quantity' => 150,
                'is_available' => true,
                'requires_prescription' => false,
                'active_ingredient' => 'Isopropyl Alcohol',
                'manufacturer' => 'Green Cross',
                'rating' => 4.2,
                'review_count' => 67,
                'tags' => json_encode(['disinfectant', 'cleaning', 'antiseptic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Band-Aid Adhesive Bandages',
                'description' => 'Sterile adhesive bandages for wound protection',
                'price' => 125.00,
                'image' => 'assets/img/bandaid.jpg',
                'category' => 'first_aid',
                'brand' => 'Band-Aid',
                'sku' => 'BND-AID-50',
                'stock_quantity' => 200,
                'is_available' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Johnson & Johnson',
                'rating' => 4.6,
                'review_count' => 189,
                'tags' => json_encode(['bandages', 'wound care', 'first aid']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hydrogen Peroxide 3%',
                'description' => 'Antiseptic solution for wound cleaning',
                'price' => 35.00,
                'image' => 'assets/img/hydrogen-peroxide.jpg',
                'category' => 'first_aid',
                'brand' => 'Generic',
                'sku' => 'HYD-PER-250',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => false,
                'active_ingredient' => 'Hydrogen Peroxide',
                'manufacturer' => 'Generic Pharma',
                'rating' => 4.1,
                'review_count' => 45,
                'tags' => json_encode(['antiseptic', 'wound cleaning', 'disinfectant']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Prescription Drugs Category
            [
                'name' => 'Amoxicillin 500mg',
                'description' => 'Antibiotic capsule for bacterial infections',
                'price' => 25.00,
                'image' => 'assets/img/amoxicillin.jpg',
                'category' => 'prescription_drugs',
                'brand' => 'Generics',
                'sku' => 'AMX-500-21',
                'stock_quantity' => 100,
                'is_available' => true,
                'requires_prescription' => true,
                'dosage' => '500mg',
                'active_ingredient' => 'Amoxicillin',
                'manufacturer' => 'Generics Pharmacy',
                'rating' => 4.2,
                'review_count' => 67,
                'tags' => json_encode(['antibiotic', 'infection', 'prescription']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Losartan 50mg',
                'description' => 'ACE inhibitor for high blood pressure',
                'price' => 180.00,
                'image' => 'assets/img/losartan.jpg',
                'category' => 'prescription_drugs',
                'brand' => 'Generics',
                'sku' => 'LOS-50-30',
                'stock_quantity' => 60,
                'is_available' => true,
                'requires_prescription' => true,
                'dosage' => '50mg',
                'active_ingredient' => 'Losartan Potassium',
                'manufacturer' => 'Generics Pharmacy',
                'rating' => 4.4,
                'review_count' => 89,
                'tags' => json_encode(['blood pressure', 'hypertension', 'prescription']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Metformin 500mg',
                'description' => 'Diabetes medication for blood sugar control',
                'price' => 95.00,
                'image' => 'assets/img/metformin.jpg',
                'category' => 'prescription_drugs',
                'brand' => 'Generics',
                'sku' => 'MET-500-30',
                'stock_quantity' => 80,
                'is_available' => true,
                'requires_prescription' => true,
                'dosage' => '500mg',
                'active_ingredient' => 'Metformin HCl',
                'manufacturer' => 'Generics Pharmacy',
                'rating' => 4.3,
                'review_count' => 112,
                'tags' => json_encode(['diabetes', 'blood sugar', 'prescription']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all products
        DB::table('products')->insert($products);

        $this->command->info('Successfully seeded ' . count($products) . ' products!');
    }
}